Check for mongo connectivity before initiating RS
This script is typically run very close to the point that the mongo
db is 'preinitialised' and/or started.

Wait for up to 5 seconds for a successful admin connection before
trying to add the replica set.

This makes for a happy automatic salt setup, but is generally useful

diff --git a/mongodb/files/mongo_initiate_replica_set b/mongodb/files/mongo_initiate_replica_set
--- a/mongodb/files/mongo_initiate_replica_set
+++ b/mongodb/files/mongo_initiate_replica_set
@@ -20,6 +20,18 @@ rs_name=$1
 master_node=$2
 shift 2
 
+WAIT_FOR_MONGOD=5
+while [ $WAIT_FOR_MONGOD -gt 0 ]; do
+  mongo -u $user -p $password --eval "pwd()" admin >/dev/null 2>&1 && break
+  WAIT_FOR_MONGOD=$(( $WAIT_FOR_MONGOD - 1 ))
+  sleep 1
+done
+
+if [ $WAIT_FOR_MONGOD -eq 0 ]; then
+  echo "Mongo is not contactable, aborting"
+  exit 1
+fi
+
 mongo -u $user -p $password --eval "printjson(rs.initiate({'_id': '${rs_name}', 'members': [{ '_id': 0, 'host': '${master_node}:27017'}]}))" admin
 if $add; then
   for secondary_node in $*; do
